# Generated by Django 3.1.2 on 2021-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0007_auto_20210711_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcitydetails',
            name='main_page_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destinationmetadetails',
            name='main_page_content',
            field=models.BooleanField(default=False),
        ),
    ]
